name: Node CI

on: [push, pull_request]

jobs:
  
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions_test
        ports:
        - 5432:5432
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815
      }
    - name: npm lint
      run: |
        npm install
        npm run lint
      env:
        CI: true 
    - name: npm test-integration
      env:
        POSTGRE_INSTANCE: localhost
        POSTGRE_DB: postgres
        POSTGRE_USER: postgres
        POSTGRE_PASSWORD: postgres
      run: |
        npm run test-integration
      env:
        CI: true
    
