name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: {
        GOOGLE_CLOUD_PROJECT: thematic-cider-139815,
        POSTGRES_DB: github_action_test,
        POSTGRE_INSTANCE: localhost
      }
    - name: npm lint
      run: |
        npm install
        npm run lint
      env:
        CI: true
    - name: npm test-integration
      run: |
        npm run test-integration
